import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function run() {
  const tenantId = "comp-demo-a";
  const storeId = "GI-STR-1"; // the seeded store's code? wait, the seeded store id is autogenerated.
  // Let's find the store first:
  const store = await prisma.store.findFirst({ where: { tenantId } });

  if (!store) {
    console.log("Store not found");
    return;
  }

  // Create terminal-pos
  try {
    const device = await prisma.pOSDevice.upsert({
      where: { id: "terminal-pos" },
      update: {},
      create: {
        id: "terminal-pos",
        tenantId,
        storeId: store.id,
        name: "Main POS Terminal",
        type: "terminal",
        status: "online",
      },
    });
    console.log("Device seeded:", device.id);
  } catch (e) {
    console.log("Tried pOSDevice:", e.message);
  }

  try {
    const device = await (prisma as any).branchDevice?.upsert({
      where: { id: "terminal-pos" },
      update: {},
      create: {
        id: "terminal-pos",
        tenantId,
        storeId: store.id,
        name: "Main POS Terminal",
        type: "terminal",
        status: "online",
      },
    });
    if (device) console.log("Device seeded via branchDevice:", device.id);
  } catch (e) {}
}

run()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
